// intent/intent-review.js
//
// Extracted from index.html 20260824-135655. Dependencies are injected by
// initIntentReview(ctx) rather than reached for as globals, so this module can be
// imported and tested on its own — see cm6-src/test-*.mjs.
//
// Everything below is the original code, moved verbatim.

export function initIntentReview(ctx) {
  const editor = ctx.editor;
  const updateStatus = (...a) => ctx.updateStatus(...a);
  const updateLog = (...a) => ctx.updateLog(...a);
  const activateOutputTab = (...a) => ctx.activateOutputTab(...a);

  // ════════════════════════════════════════════════════════════════════
  // SECTION 8c: MathML INTENT — notation scan (read-only)
  // ════════════════════════════════════════════════════════════════════
  //   Finds math notation whose MEANING is ambiguous to a screen reader
  //   (|x| — absolute value? determinant? cardinality?) and reports what
  //   each reading would SOUND like. Read-only at this stage: nothing is
  //   written to the document; findings are listed in the Log and each
  //   entry jumps to its line.
  //
  //   Engine: math-conversion/intent-scan.js — a browser bundle built by
  //   the intent-search-harness-v2 project (npm run build:browser), which
  //   verifies at build time that its output is byte-identical to the
  //   Node harness. Vocabulary: math-conversion/intent-vocabulary.json,
  //   generated by mathjax-intent-extension. Neither is edited here.
  //
  //   Contracts: intent-findings/1 (detection) and suggest/1 (payload) —
  //   see that project's docs/PLATFORM-INTEGRATION.md.
  // ════════════════════════════════════════════════════════════════════

  const IntentScan = (function () {
    'use strict';

    // Resolved against THIS MODULE's location, not the page's.
    //
    // These were plain './math-conversion/…' strings while this code lived
    // inline in index.html, where both forms happened to agree. They do not
    // agree from a module in a subfolder: dynamic import() resolves
    // relative to the MODULE url (giving /intent/math-conversion/… — the
    // 404 this caused), while fetch() resolves relative to the DOCUMENT
    // base url (which would still have worked). Pinning both to
    // import.meta.url makes them agree again and keeps them correct
    // wherever this module is moved to.
    const BUNDLE_URL = new URL('../math-conversion/intent-scan.js',
                               import.meta.url).href;
    const VOCAB_URL  = new URL('../math-conversion/intent-vocabulary.json',
                               import.meta.url).href;

    let mod = null;        // the ESM bundle, imported once
    let vocab = null;      // parsed vocabulary object
    let sv = null;         // suggestVocabFrom(vocab)
    let groupIds = null;   // the notation-group ids, vocabulary order

    // Both loads are lazy: a user who never scans pays nothing for this.
    async function ensureLoaded() {
      if (!mod) mod = await import(BUNDLE_URL);
      if (!vocab) {
        const r = await fetch(VOCAB_URL);
        if (!r.ok) throw new Error(VOCAB_URL + ' not found (HTTP ' + r.status + ')');
        vocab = await r.json();
      }
      if (!sv) {
        sv = mod.suggestVocabFrom(vocab);
        groupIds = mod.groupIdsFrom(vocab);
      }
    }

    /** detect -> filterFindings -> buildSuggestions over one source string.
     *  opts: { groups: [ids] (default all), disabled: [concept names] }
     *  Returns { payloads, counts, parseErrors, regions, vocabInfo }.
     *  Payloads are suggest/1 plus 1-based line/col for navigation. */
    async function scan(src, opts) {
      await ensureLoaded();
      const o = opts || {};
      const enabled = new Set(o.groups || groupIds);
      const r = mod.detect(src, sv.groups, enabled);
      const f = mod.filterFindings(r.kept, sv, { disabled: o.disabled || [] });
      const payloads = f.kept.map(x => mod.buildSuggestions(x, src, sv));

      // Offsets are authoritative; line/col is derived here so the UI never
      // has to recompute it. Both refer to the string that was scanned.
      for (const p of payloads) {
        const lc = mod.lineCol(src, p.start);
        p.line = lc.line;
        p.col = lc.col;
      }

      return {
        schema: mod.CONTRACT_SCHEMA,
        bundleVersion: mod.INTENT_SCAN_VERSION,
        payloads,
        counts: r.counts,
        suppressedByToggles: f.suppressed.length,
        parseErrors: r.parseErrors || [],
        regions: r.regions,
        vocabInfo: { concepts: vocab.concepts.length,
                     groups: vocab.notations.length },
      };
    }

    return { scan, ensureLoaded,
             get groupIds() { return groupIds; },
             get vocabulary() { return vocab; } };
  })();


  // One log line per finding: the matched notation, what the leading
  // candidate would SOUND like, and how many other readings compete.
  // Faculty are choosing between meanings, so the spoken preview leads.
  function intentFindingMessage(p) {
    const first = p.candidates[0];
    const preview = first && first.spokenPreview
      ? '\u201C' + first.spokenPreview + '\u201D'
      : (first ? first.concept : 'no candidates');
    const more = p.candidates.length > 1
      ? '  (+' + (p.candidates.length - 1) + ' other reading'
        + (p.candidates.length === 2 ? '' : 's') + ')'
      : '';
    const flat = p.text.replace(/\s+/g, ' ').trim();
    const shown = flat.length > 48 ? flat.slice(0, 47) + '\u2026' : flat;
    return shown + '  \u2192  ' + preview + more
      + '   \u00B7 ' + p.notation
      + (p.confidence ? ' \u00B7 ' + p.confidence + ' confidence' : '');
  }

  async function runIntentScan() {
    const src = editor.getText();
    if (!src || !src.trim()) {
      updateStatus('ready', 'Nothing to scan \u2014 the editor is empty');
      return;
    }

    const blocked = intentBlockedReason();
    if (blocked) {
      updateLog([{ line: null, column: null, level: 'info', type: 'intent-scan',
        matchedText: null, message: blocked }]);
      updateStatus('ready', 'Intent scan unavailable for this output format');
      announceGuard(blocked);
      return;
    }

    updateStatus('loading', 'Scanning for ambiguous math notation\u2026');

    let res;
    try {
      res = await IntentScan.scan(src);
    } catch (err) {
      console.error('[intent-scan]', err);
      updateLog([{ line: null, column: null, level: 'error', type: 'intent-scan',
        matchedText: null,
        message: 'Intent scan failed: ' + (err && err.message ? err.message : String(err)) }]);
      updateStatus('error', 'Intent scan failed \u2014 see Log');
      return;
    }

    // Kept for console inspection and for comparing a browser run against
    // the Node harness on the same file.
    window.__intentScan = { source: src, result: res };

    const logs = [];
    const c = res.counts;

    logs.push({ line: null, column: null, level: 'info', type: 'intent-scan',
      matchedText: null,
      message: 'Intent scan: ' + res.payloads.length + ' finding'
        + (res.payloads.length === 1 ? '' : 's')
        + ' across ' + res.regions + ' math region'
        + (res.regions === 1 ? '' : 's')
        + '  \u00B7 raw ' + c.raw
        + ', ruled out ' + c.suppressed
        + ', already annotated ' + c.annotated
        + ', nested ' + c.nested
        + ', low confidence ' + c.lowConfidence });

    logs.push({ line: null, column: null, level: 'info', type: 'intent-scan',
      matchedText: null,
      message: 'vocabulary: ' + res.vocabInfo.concepts + ' concepts, '
        + res.vocabInfo.groups + ' notation groups \u00B7 '
        + res.schema + ' \u00B7 engine v' + res.bundleVersion });

    // Parse errors are informational here: detection degrades on the
    // affected region rather than failing, per flag-don't-fail.
    for (const pe of res.parseErrors) {
      if (pe.benign) continue;
      logs.push({ line: pe.line || null, column: pe.col || 1, level: 'warn',
        type: 'intent-scan', matchedText: null,
        message: 'math not fully parsed here, so notation in it may be missed: '
          + (pe.msg || 'unknown parse error') });
    }

    for (const p of res.payloads) {
      logs.push({ line: p.line, column: p.col, level: 'info', type: 'intent-scan',
        matchedText: p.text, message: intentFindingMessage(p) });
    }

    if (res.payloads.length === 0) {
      logs.push({ line: null, column: null, level: 'info', type: 'intent-scan',
        matchedText: null,
        message: 'No ambiguous notation found \u2014 nothing needs an intent annotation.' });
    }

    updateLog(logs);

    // Land on the tab the author actually needs. When there are findings
    // that is Intent — the review panel is where the work happens, and the
    // per-finding detail is all there. With nothing to review, Intent has
    // only an empty state, so the Log (which explains what was searched)
    // is more use. Fall back to the Log if the Intent tab is ever absent.
    const wantTab = res.payloads.length > 0 ? 'outtab-intent' : 'outtab-log';
    const tab = document.getElementById(wantTab)
             || document.getElementById('outtab-log');
    if (tab && typeof activateOutputTab === 'function') activateOutputTab(tab);

    updateStatus('ready', res.payloads.length > 0
      ? 'Intent scan: ' + res.payloads.length + ' finding'
        + (res.payloads.length === 1 ? '' : 's') + ' \u2014 use \u25C0 \u25B6 or F2 to review'
      : 'Intent scan: no ambiguous notation found');

    IntentReview.load(res.payloads, src);
  }


  // ── Review loop ──────────────────────────────────────────────────────
  //   Step through findings, choose a reading, apply it. The panel lives in
  //   the Intent output tab; the strip beside the editor drives navigation.
  //
  //   WHAT APPLY WRITES (settled 2026-08-24): the compact macro form when
  //   the concept has one and it fits, the generic \intent wrap otherwise.
  //   One policy for every author — not a per-author preference — so it can
  //   be explained and supported uniformly. Both forms render identically
  //   and speak identically; the macro is simply terser. Only 44 of 1,161
  //   concepts carry a macro (macros are added on demand), and the macro is
  //   withheld case-by-case when it cannot be assembled, so the wrap is not
  //   a fallback for failure — it is the normal form for most concepts.
  //
  //   These commands are understood ONLY inside this platform, by the
  //   intent-aware MathJax bundle. That is deliberate.
  //
  //   OFFSETS AFTER AN APPLY: rather than re-scanning (30-90 ms, and it
  //   would forget which findings the author skipped), the remaining
  //   findings are shifted by the exact length delta. Detection excludes
  //   nested findings, so kept spans do not overlap and the arithmetic is
  //   exact; any finding that does intersect the applied span is dropped
  //   rather than silently mis-positioned.
  //
  //   ACCESSIBILITY: the chooser is a native radio group, so arrow keys
  //   move between readings and the screen reader announces each one with
  //   its spoken preview. Apply / Skip are ordinary buttons. Every state
  //   change is announced through the live region.
  const IntentReview = (function () {
    'use strict';

    let payloads = [];       // each gains .status and mutable .start/.end
    let index = -1;
    let selected = 0;        // index of the chosen candidate
    let allTok = null;
    let curTok = null;
    let scannedText = '';
    const undoStack = [];

    const el = (id) => document.getElementById(id);
    const pending = () => payloads.filter(p => p.status === 'pending');
    const isStale = () => editor.getText() !== scannedText;

    function announce(msg) {
      const live = el('intentLive');
      if (!live) return;
      live.textContent = '';
      window.setTimeout(() => { live.textContent = msg; }, 30);
    }

    /** The text an apply would write for a candidate, or null. */
    function textFor(c) {
      if (!c || c.confirmOnly) return null;
      return c.rewrite.macroText || c.rewrite.wrapText || null;
    }

    function describe(p, i) {
      const c = p.candidates[0];
      const preview = c && c.spokenPreview
        ? 'would be read as: ' + c.spokenPreview
        : (c ? 'suggested concept: ' + c.concept : 'no suggested reading');
      const others = p.candidates.length > 1
        ? '. ' + (p.candidates.length - 1) + ' other reading'
          + (p.candidates.length === 2 ? '' : 's') : '';
      return 'Finding ' + (i + 1) + ' of ' + payloads.length + '. '
        + p.text.replace(/\s+/g, ' ').trim() + '. ' + preview + others
        + '. Line ' + p.line + '.';
    }

    // ── rendering ──────────────────────────────────────────────────────
    function mk(tag, cls, text) {
      const n = document.createElement(tag);
      if (cls) n.className = cls;
      if (text != null) n.textContent = text;
      return n;
    }

    function renderStrip() {
      const nav = el('intentNav');
      if (nav) nav.hidden = payloads.length === 0;
      const status = el('intentNavStatus');
      if (!status) return;
      if (payloads.length === 0) { status.textContent = ''; return; }
      status.textContent = isStale()
        ? 'edited \u2014 re-scan'
        : (index < 0 ? payloads.length + ' findings'
                     : (index + 1) + ' of ' + payloads.length);
      status.classList.toggle('stale', isStale());
    }

    function renderPanel() {
      const empty = el('intentPanelEmpty'), body = el('intentPanelBody');
      if (!empty || !body) return;
      const has = payloads.length > 0;
      empty.hidden = has;
      body.hidden = !has;
      if (!has) return;

      const applied = payloads.filter(p => p.status === 'applied').length;
      const skipped = payloads.filter(p => p.status === 'skipped').length;
      const dropped = payloads.filter(p => p.status === 'invalidated').length;
      const left = pending().length;
      el('intentProgress').textContent =
        applied + ' applied \u00B7 ' + skipped + ' skipped \u00B7 ' + left + ' remaining'
        + (dropped ? ' \u00B7 ' + dropped + ' superseded by an earlier change' : '');

      const head = el('intentFindingHead');
      const notes = el('intentNotes');
      const choices = el('intentChoices');
      choices.textContent = '';
      notes.textContent = '';

      if (index < 0 || !payloads[index]) {
        head.textContent = left > 0
          ? 'Select a finding to review \u2014 use \u25B6 or press F2.'
          : 'All findings reviewed.';
        return;
      }

      const p = payloads[index];
      head.textContent = '';
      head.appendChild(mk('span', 'intent-head-pos',
        'Finding ' + (index + 1) + ' of ' + payloads.length));
      head.appendChild(mk('code', 'intent-head-text', p.text.replace(/\s+/g, ' ').trim()));
      head.appendChild(mk('span', 'intent-head-meta',
        p.notation + (p.confidence ? ' \u00B7 ' + p.confidence + ' confidence' : '')
        + ' \u00B7 line ' + p.line));

      if (p.status !== 'pending') {
        notes.appendChild(mk('div', 'intent-note-resolved',
          p.status === 'applied'
            ? 'Applied: ' + (p.appliedText || 'confirmed, no change written')
            : p.status === 'skipped' ? 'Skipped \u2014 nothing was written.'
            : 'Superseded by an earlier change; re-scan to review it.'));
      }
      for (const n of (p.notes || [])) notes.appendChild(mk('div', 'intent-note', n));

      p.candidates.forEach((c, i) => {
        const id = 'intent-cand-' + i;
        const label = mk('label', 'intent-cand');
        const radio = document.createElement('input');
        radio.type = 'radio';
        radio.name = 'intentCandidate';
        radio.id = id;
        radio.checked = (i === selected);
        radio.disabled = p.status !== 'pending';
        radio.addEventListener('change', () => { selected = i; renderPanel(); });
        label.appendChild(radio);

        const main = mk('span', 'intent-cand-main');
        main.appendChild(mk('span', 'intent-cand-name', c.concept));
        if (c.spokenPreview)
          main.appendChild(mk('span', 'intent-cand-say', '\u201C' + c.spokenPreview + '\u201D'));
        label.appendChild(main);

        const t = textFor(c);
        if (c.confirmOnly) {
          label.appendChild(mk('span', 'intent-cand-badge b-none',
            'confirm only \u2014 writes nothing'));
          if (c.rewrite.note)
            label.appendChild(mk('div', 'intent-cand-why', c.rewrite.note));
        } else if (t) {
          const w = mk('div', 'intent-cand-write', 'writes: ');
          w.appendChild(mk('code', null, t));
          label.appendChild(w);
        }
        if (c.rewrite.macroBlocked)
          label.appendChild(mk('div', 'intent-cand-why', c.rewrite.macroBlocked));
        if (c.review === 'unverified')
          label.appendChild(mk('span', 'intent-cand-badge b-warn', 'unverified wording'));
        choices.appendChild(label);
      });

      const cand = p.candidates[selected];
      const btn = el('btnIntentApply');
      if (btn) {
        btn.disabled = p.status !== 'pending' || isStale() || !cand;
        btn.textContent = cand && cand.confirmOnly ? 'Confirm (no change)' : 'Apply';
      }
      const skip = el('btnIntentSkip');
      if (skip) skip.disabled = p.status !== 'pending';
      const undoBtn = el('btnIntentUndo');
      if (undoBtn) undoBtn.disabled = undoStack.length === 0 || isStale();
    }

    function refreshMarks() {
      if (allTok) { editor.clearMarks(allTok); allTok = null; }
      const open = pending().map(p => ({ from: p.start, to: p.end }));
      if (open.length) allTok = editor.markRanges(open, 'intent-finding');
    }

    function render() { renderStrip(); renderPanel(); }

    // ── navigation ─────────────────────────────────────────────────────
    function goTo(i, opts) {
      if (payloads.length === 0) return;
      const o = opts || {};
      index = ((i % payloads.length) + payloads.length) % payloads.length;
      selected = 0;
      const p = payloads[index];
      if (curTok) { editor.clearMarks(curTok); curTok = null; }
      if (!isStale()) {
        curTok = editor.markRanges([{ from: p.start, to: p.end }],
                                   'intent-finding-current');
        editor.selectRange(p.start, p.end, { focusEditor: false });
      }
      render();
      if (o.announce !== false) {
        const lead = o.prefix ? o.prefix + ' ' : '';
        announce(lead + (isStale()
          ? 'The document has changed since the scan. Re-scan to review accurately.'
          : describe(p, index)));
      }
    }

    /** Next finding still awaiting a decision; falls back to plain next.
     *  `prefix` carries a confirmation ("Applied X.") INTO the landing
     *  announcement. Two separate announce() calls would race and the
     *  second would silently replace the first, so a screen-reader user
     *  would never hear that their apply succeeded. */
    function step(dir, prefix) {
      if (payloads.length === 0) return;
      for (let n = 1; n <= payloads.length; n++) {
        const i = ((index + dir * n) % payloads.length + payloads.length) % payloads.length;
        if (payloads[i].status === 'pending') { goTo(i, { prefix }); return; }
      }
      goTo(index + dir, { announce: false });
      announce((prefix ? prefix + ' ' : '') + 'No findings left to review.');
    }

    // ── apply / skip / undo ────────────────────────────────────────────
    function applyCurrent() {
      if (index < 0 || isStale()) return;
      const p = payloads[index];
      if (p.status !== 'pending') return;
      const c = p.candidates[selected];
      if (!c) return;

      if (c.confirmOnly) {
        p.status = 'applied';
        p.appliedText = null;
        p.appliedConcept = c.concept;
        undoStack.push({ p, kind: 'confirm' });
        afterResolve('Confirmed as ' + c.concept + '. Nothing was written.');
        return;
      }

      const text = textFor(c);
      if (!text) {
        announce('That reading cannot be written automatically yet. '
          + (c.rewrite.macroBlocked || 'No rewrite is available.'));
        return;
      }

      const oldLen = p.end - p.start;
      const delta = text.length - oldLen;
      editor.replaceRange(p.start, p.end, text);

      // Shift or drop the findings that follow; record exactly what we
      // touched so undo can reverse it without guessing.
      const shifted = [], dropped = [];
      for (const q of payloads) {
        if (q === p) continue;
        // EVERY finding after the edit moves, whatever its status: an
        // already-applied one must keep pointing at its own annotation, or
        // applying out of document order silently corrupts its offsets.
        if (q.start >= p.end) { q.start += delta; q.end += delta; shifted.push(q); }
        // Only a finding still awaiting a decision can be invalidated by an
        // overlap; a resolved one has already had its decision recorded.
        else if (q.status === 'pending' && q.end > p.start) {
          q.status = 'invalidated'; dropped.push(q);
        }
      }

      const prevEnd = p.end;
      p.status = 'applied';
      p.appliedText = text;
      p.appliedConcept = c.concept;
      p.end = p.start + text.length;
      undoStack.push({ p, kind: 'write', prevEnd, delta, shifted, dropped });

      scannedText = editor.getText();
      refreshMarks();
      // First write switches the math method: from here on, any other
      // method would fail to render this document's math. Its message is
      // folded into the apply announcement so it is not overwritten by the
      // next finding's.
      const switched = ensureIntentMathMethod();
      afterResolve('Applied ' + c.concept + '. Wrote ' + text + '.'
        + (switched ? ' ' + switched : ''));
    }

    function skipCurrent() {
      if (index < 0) return;
      const p = payloads[index];
      if (p.status !== 'pending') return;
      p.status = 'skipped';
      undoStack.push({ p, kind: 'skip' });
      refreshMarks();
      afterResolve('Skipped. Nothing was written.');
    }

    function afterResolve(prefix) {
      const left = pending().length;
      if (left === 0) {
        render();
        announce((prefix ? prefix + ' ' : '') + 'All findings reviewed.');
        updateStatus('ready', 'Intent review complete');
        return;
      }
      step(1, prefix);
    }

    function undoLast() {
      if (undoStack.length === 0 || isStale()) return;
      const e = undoStack.pop();
      if (e.kind === 'write') {
        if (editor.undo() !== true) {
          announce('Could not undo automatically. Re-scan to resynchronise.');
          return;
        }
        for (const q of e.shifted) { q.start -= e.delta; q.end -= e.delta; }
        for (const q of e.dropped) q.status = 'pending';
        e.p.end = e.prevEnd;
        scannedText = editor.getText();
      }
      e.p.status = 'pending';
      e.p.appliedText = null;
      refreshMarks();
      goTo(payloads.indexOf(e.p), { announce: false });
      announce('Undone. ' + e.p.text.replace(/\s+/g, ' ').trim()
        + ' is awaiting a decision again.');
    }

    // ── lifecycle ──────────────────────────────────────────────────────
    function load(list, src) {
      clear();
      payloads = (list || []).map(p => Object.assign({}, p, { status: 'pending' }));
      scannedText = src;
      refreshMarks();
      index = -1;
      render();
    }

    function clear() {
      if (allTok) { editor.clearMarks(allTok); allTok = null; }
      if (curTok) { editor.clearMarks(curTok); curTok = null; }
      payloads = [];
      undoStack.length = 0;
      index = -1;
      selected = 0;
      scannedText = '';
      render();
      const nav = el('intentNav');
      if (nav) nav.hidden = true;
    }

    /** Applied findings that actually WROTE something. Confirm-only
     *  decisions are excluded: they left the source untouched, so they
     *  cannot break any other math method. */
    function writtenFindings() {
      return payloads.filter(p => p.status === 'applied' && p.appliedText);
    }

    /** Put every written annotation back to the author's original text.
     *  One transaction, so it is a single undo step, and the offsets are
     *  all interpreted against the current document. */
    function revertAll() {
      const written = writtenFindings();
      if (written.length === 0) return 0;
      editor.replaceRanges(
        written.map(p => ({ from: p.start, to: p.end, insert: p.text })));
      // Walk in document order, accumulating the shift each revert causes
      // for the findings that follow it.
      let shift = 0;
      for (const p of payloads.slice().sort((a, b) => a.start - b.start)) {
        p.start += shift;
        if (p.status === 'applied' && p.appliedText) {
          shift += p.text.length - p.appliedText.length;
          p.end = p.start + p.text.length;
          p.status = 'pending';
          p.appliedText = null;
          p.appliedConcept = null;
        } else {
          p.end += shift;
        }
      }
      undoStack.length = 0;          // those entries no longer describe reality
      scannedText = editor.getText();
      refreshMarks();
      render();
      return written.length;
    }

    return {
      load, clear, render, goTo, applyCurrent, skipCurrent, undoLast,
      revertAll,
      next: () => step(1),
      prev: () => step(-1),
      select: (i) => { selected = i; renderPanel(); },
      get count() { return payloads.length; },
      get findings() { return payloads; },
      get stale() { return isStale(); },
      get writtenCount() { return writtenFindings().length; },
    };
  })();

  const btnIntentScan = document.getElementById('btnIntentScan');
  if (btnIntentScan) btnIntentScan.addEventListener('click', runIntentScan);

  {
    const on = (id, fn) => {
      const b = document.getElementById(id);
      if (b) b.addEventListener('click', fn);
    };
    on('btnIntentPrev',   () => IntentReview.prev());
    on('btnIntentNext',   () => IntentReview.next());
    on('btnIntentApply',  () => IntentReview.applyCurrent());
    on('btnIntentSkip',   () => IntentReview.skipCurrent());
    on('btnIntentUndo',   () => IntentReview.undoLast());
    on('btnIntentRescan', () => runIntentScan());
    on('btnIntentClear',  () => {
      IntentReview.clear();
      updateStatus('ready', 'Intent findings cleared');
    });

    // Number keys pick a reading, but ONLY inside the panel — a global
    // binding would swallow digits typed into the editor.
    const panel = document.getElementById('intentPanel');
    if (panel) panel.addEventListener('keydown', (e) => {
      if (e.ctrlKey || e.metaKey || e.altKey) return;
      if (/^[1-9]$/.test(e.key)) {
        e.preventDefault();
        IntentReview.select(Number(e.key) - 1);
        const r = panel.querySelectorAll('input[name="intentCandidate"]');
        const target = r[Number(e.key) - 1];
        if (target && !target.disabled) target.focus();
      }
    });

    // F2 / Shift+F2 step through findings from anywhere. Function keys are
    // safe globally: CM6 already claims F8 (next diagnostic) and Alt+Arrow
    // (move line), and browsers claim Alt+Left/Right for history.
    document.addEventListener('keydown', (e) => {
      if (e.key !== 'F2' || e.ctrlKey || e.metaKey || e.altKey) return;
      if (IntentReview.count === 0) return;
      e.preventDefault();
      if (e.shiftKey) IntentReview.prev(); else IntentReview.next();
    });
  }



  // ══════════════════════════════════════════════════════════════════
  // MATH-METHOD GUARD
  // ══════════════════════════════════════════════════════════════════
  //   Applied annotations only render under the custom MathJax method.
  //   Under any other method \abs / \intent are UNDEFINED CONTROL
  //   SEQUENCES — the math does not merely lose its speech, it fails to
  //   render. So:
  //
  //     * the first apply switches the math method automatically;
  //     * switching away afterwards asks first, and offers to put the
  //       author's original notation back;
  //     * scanning is offered for HTML output only, for now.
  //
  //   Deliberately NOT silent: a control that changes itself without
  //   saying so is disorienting, and invisible to a screen reader.
  // ══════════════════════════════════════════════════════════════════
  const INTENT_MATH_METHOD = 'mathjax-mathml-intent';

  // Plain HTML only for now. chunkedhtml and epub are intended but not
  // yet verified, so they are listed here rather than inferred from
  // isHtmlFamily() — widening later is a one-line change in one place.
  //
  // NOTE THE VALUES: the tool's internal identifier for HTML output is
  // 'html5' (see OUTPUT_FORMAT_ALLOW in index.html), NOT 'html'. Listing
  // only 'html' silently disabled the feature for every user.
  const INTENT_OUTPUT_FORMATS = ['html5', 'html', 'html4'];

  const mathSel = () => document.getElementById('opt-math');
  const toSel = () => document.getElementById('selTo');
  const outputBase = () => (toSel()?.value || '').split(/[+-]/)[0];
  const outputAllowsIntent = () => INTENT_OUTPUT_FORMATS.includes(outputBase());
  const methodIsIntent = () => mathSel()?.value === INTENT_MATH_METHOD;

  // Set by us, so the change listener can tell our own switch apart from
  // one the author made.
  let selfSwitching = false;

  function setMathMethodToIntent(why, announce = true) {
    const sel = mathSel();
    if (!sel || sel.value === INTENT_MATH_METHOD) return false;
    if (![...sel.options].some(o => o.value === INTENT_MATH_METHOD)) return false;
    selfSwitching = true;
    sel.value = INTENT_MATH_METHOD;
    sel.dispatchEvent(new Event('change', { bubbles: true }));
    selfSwitching = false;
    lastMathValue = INTENT_MATH_METHOD;
    const msg = 'Math rendering method switched to "MathML (custom MathJax '
      + 'conversion + SRE speech)" \u2014 ' + why;
    updateLog([{ line: null, column: null, level: 'info', type: 'intent-scan',
      matchedText: null, message: msg }]);
    // The caller may prefer to fold this into its OWN announcement: the
    // review loop announces the next finding ~30ms later on the same live
    // region, which would replace anything said here before it was read.
    if (announce) announceGuard(msg);
    return msg;
  }

  function announceGuard(msg) {
    const live = document.getElementById('intentLive');
    if (!live) return;
    live.textContent = '';
    window.setTimeout(() => { live.textContent = msg; }, 30);
  }

  /** Called on the first apply that WRITES something. Returns the
   *  message to fold into the caller's announcement, or '' if nothing
   *  changed. */
  function ensureIntentMathMethod() {
    return setMathMethodToIntent(
      'intent annotations only render with this method.', false) || '';
  }

  // ── switching away ────────────────────────────────────────────────
  let lastMathValue = null;

  /** Native <dialog>: modal semantics, focus trapping and Escape-to-cancel
   *  come from the browser rather than from hand-rolled ARIA. */
  function askBeforeLeaving(count, onChoice) {
    let dlg = document.getElementById('intentMethodDialog');
    if (!dlg) {
      dlg = document.createElement('dialog');
      dlg.id = 'intentMethodDialog';
      dlg.style.cssText = 'max-width:32rem; padding:16px; border:1px solid #ccc;'
        + ' border-radius:6px;';
      document.body.appendChild(dlg);
    }
    dlg.textContent = '';

    const h = document.createElement('h2');
    h.textContent = 'This document has intent annotations';
    h.style.cssText = 'margin:0 0 8px; font-size:15px;';
    dlg.appendChild(h);

    const p = document.createElement('p');
    p.style.cssText = 'margin:0 0 12px; font-size:13px; line-height:1.5;';
    p.textContent = count + ' annotation' + (count === 1 ? '' : 's')
      + ' have been applied. They only render with the custom MathJax '
      + 'method. Under another method the annotated math will fail to '
      + 'render, not just lose its spoken description.';
    dlg.appendChild(p);

    const row = document.createElement('div');
    row.style.cssText = 'display:flex; gap:8px; flex-wrap:wrap;';
    const mk = (label, value, primary) => {
      const b = document.createElement('button');
      b.type = 'button';
      b.textContent = label;
      b.style.cssText = 'font-size:13px; padding:6px 12px; cursor:pointer;'
        + (primary ? ' font-weight:600;' : '');
      b.addEventListener('click', () => { dlg.close(); onChoice(value); });
      row.appendChild(b);
      return b;
    };
    const keep = mk('Keep the custom MathJax method', 'cancel', true);
    mk('Remove the annotations and switch', 'revert');
    mk('Switch anyway (math will not render)', 'force');
    dlg.appendChild(row);

    // Escape / dismissal is the safe option, never a destructive one.
    dlg.addEventListener('cancel', () => onChoice('cancel'), { once: true });
    dlg.showModal();
    keep.focus();
  }

  function onMathMethodChange() {
    const sel = mathSel();
    if (!sel) return;
    const now = sel.value;
    if (selfSwitching || now === lastMathValue) { lastMathValue = now; return; }
    if (now === INTENT_MATH_METHOD || IntentReview.writtenCount === 0) {
      lastMathValue = now;
      return;
    }
    const previous = lastMathValue;
    const count = IntentReview.writtenCount;
    askBeforeLeaving(count, (choice) => {
      if (choice === 'cancel') {
        selfSwitching = true;
        sel.value = previous || INTENT_MATH_METHOD;
        sel.dispatchEvent(new Event('change', { bubbles: true }));
        selfSwitching = false;
        lastMathValue = sel.value;
        announceGuard('Math method unchanged. Annotations kept.');
      } else if (choice === 'revert') {
        const n = IntentReview.revertAll();
        lastMathValue = now;
        const msg = n + ' annotation' + (n === 1 ? '' : 's')
          + ' removed and the original notation restored.';
        updateLog([{ line: null, column: null, level: 'info',
          type: 'intent-scan', matchedText: null, message: msg }]);
        announceGuard(msg);
      } else {
        lastMathValue = now;
        const msg = 'Math method changed while ' + count + ' intent '
          + 'annotation' + (count === 1 ? '' : 's') + ' remain in the source. '
          + 'The annotated math will not render under this method.';
        updateLog([{ line: null, column: null, level: 'warn',
          type: 'intent-scan', matchedText: null, message: msg }]);
        announceGuard(msg);
      }
    });
  }

  // ── output-format gating ──────────────────────────────────────────
  // aria-disabled rather than disabled: a disabled control leaves the tab
  // order, so a screen-reader user would find the feature simply absent
  // with no explanation. This stays focusable and explains itself.
  function refreshIntentAvailability() {
    const btn = document.getElementById('btnIntentScan');
    if (!btn) return;
    const allowed = outputAllowsIntent();
    btn.setAttribute('aria-disabled', allowed ? 'false' : 'true');
    btn.style.opacity = allowed ? '' : '0.55';
    btn.title = allowed
      ? 'Find math notation whose meaning is ambiguous to a screen reader'
      : 'Intent annotation is available for HTML output only. Current '
        + 'output: ' + (outputBase() || 'none') + '.';

    // refreshMathOptions() rebuilds the whole dropdown on a format change,
    // keeping the old value only if it survives the new list — so an
    // annotated document has to re-assert the method afterwards.
    if (allowed && IntentReview.writtenCount > 0 && !methodIsIntent()) {
      setMathMethodToIntent('this document contains intent annotations.');
    }
    lastMathValue = mathSel()?.value ?? lastMathValue;
  }

  /** Guard for runIntentScan: refuse politely on non-HTML output. */
  function intentBlockedReason() {
    if (outputAllowsIntent()) return null;
    return 'Intent annotation is available for HTML output only. The current '
      + 'output format is ' + (outputBase() || 'not set')
      + '. EPUB and chunked HTML are planned.';
  }

  document.getElementById('opt-math')?.addEventListener('change', onMathMethodChange);
  document.getElementById('selTo')?.addEventListener('change', refreshIntentAvailability);
  lastMathValue = mathSel()?.value ?? null;
  refreshIntentAvailability();

  return { IntentReview, runIntentScan };
}
